# docker-compose.yml

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: 'Europe/Rome'
      # App credentials will be overridden by the .env file
      WEB_PORT: ${WEB_PORT:-8087}
      APP_URL: ${APP_URL:-http://localhost:${WEB_PORT:-8087}}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
    ports:
      - "${WEB_PORT:-8087}:80"
    volumes:
      - ./:/var/www/html

  mysql:
    image: mariadb:10.11
    # Use a separate env for docker to avoid laravel conflicts
    env_file:
      - docker.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      TZ: 'Europe/Rome'
    ports:
      - "${DB_PORT:-3380}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT:-8090}:80"
    environment:
      - UPLOAD_LIMIT=1G
      - PMA_HOST=mysql
      - PMA_PORT=${DB_PORT:-3306}
      - PMA_USER=${DB_USERNAME:-root}
      - PMA_PASSWORD=${DB_PASSWORD:-root}
    
  mailhog:
    image: mailhog/mailhog
    ports:
        - "${MAILHOG_SMTP_PORT:-1025}:1025"
        - "${MAILHOG_WEB_PORT:-8025}:8025"